In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Define the questions and answers
questions = ["hi","what is your name?","bye"]
answers = ["Hello","My name is Chatbot.","Good bye"]

In [3]:
# Define a vocabulary and mapping from words to indices
l=(" ".join(questions)).split()
vocab={j:i for i,j in enumerate(l)}
print(vocab)

{'hi': 0, 'what': 1, 'is': 2, 'your': 3, 'name?': 4, 'bye': 5}


In [4]:
# Convert the questions and answers to numerical form
X = np.zeros((len(questions), len(vocab)), dtype=np.float32)
Y = np.zeros((len(answers), len(answers)), dtype=np.float32)
for i, question in enumerate(questions):
    for word in question.lower().split():
        if word in vocab:
            X[i, vocab[word]] = 1.0
    Y[i, i] = 1.0
print(X)
print(Y)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Define the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(len(vocab),)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(len(answers), activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [6]:
# Train the model on the questions and answers
model.fit(X, Y, epochs=10)

Epoch 1/10
1/1 [==============================] - 1s 954ms/step - loss: 1.1684 - accuracy: 0.3333
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 1.1420 - accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 1.1165 - accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 1.0926 - accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 1.0697 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 1.0495 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 1.0300 - accuracy: 0.6667
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 1.0107 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 0.9929 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9757 - accuracy: 1.0000


In [7]:
# Define a function to generate a response from the model
def generate_response(input_text):
    x = np.zeros((1, len(vocab)), dtype=np.float32)
    for word in input_text.lower().split():
        if word in vocab:
            x[0, vocab[word]] = 1.0
    y = model.predict(x)[0]
    index = np.argmax(y)
    print(index)
    return answers[index]

In [ ]:
# Ask for user input and generate a response
while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        break
    response = generate_response(user_input)
    print("Chatbot:", response)

You: hi
1/1 [==============================] - 0s 93ms/step
0
Chatbot: Hello
You: bye
1/1 [==============================] - 0s 21ms/step
2
Chatbot: Good bye
You: what is your name
1/1 [==============================] - 0s 24ms/step
1
Chatbot: My name is Chatbot.
You: what is the time now
1/1 [==============================] - 0s 22ms/step
0
Chatbot: Hello
