<a href="https://colab.research.google.com/github/aritroo/Lung-Disease-Detection-SEM-VI-Mini-Project-/blob/master/dl2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import cifar10

plt.rcParams['figure.figsize'] = (10.0,8.0)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

In [ ]:
(X_train,y_train),(X_test,y_test) = cifar10.load_data()

170498071/170498071 [==============================] - 2s 0us/step


In [ ]:
print("Number of training images: ", len(X_train))
print("Number of testing images : ", len(X_test))
print("Size of each image  : ", len(X_train[0]),"x",len(X_train[0][0]),"x",len(X_train[0][0][0]))

Number of training images:  50000
Number of testing images :  10000
Size of each image  :  32 x 32 x 3


In [ ]:
X_train = np.reshape(X_train ,(X_train.shape[0],-1))
X_test = np.reshape(X_test,(X_test.shape[0],-1))
print(X_train.shape[0])

50000


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
#Train Model and predict
k = 4
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train.ravel())


In [ ]:
y_test_pred = neigh.predict(X_test)
num_correct = np.sum(y_test_pred == y_test.ravel())
accuracy = float(num_correct)/ len(X_test)
print('Got %d / %d correct => accuracy : %f' %(num_correct,len(X_test),accuracy))

Got 3398 / 10000 correct => accuracy : 0.339800


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_pred,y_test.ravel())
print(cm)

[[563 165 125  92  90  81  31 112 168 191]
 [ 10 229   6   9   3   4   4  10  18  73]
 [106 119 453 235 270 225 290 187  49 121]
 [ 15  42  50 220  39 163  67  55  33  66]
 [ 50 135 211 167 462 159 283 259  51  96]
 [  5  31  35 107  22 221  32  48  16  21]
 [ 30  52  59 102  51  82 260  54  10  45]
 [  5   9   7  21  12  14   3 216   5  19]
 [210 199  51  41  50  47  28  55 643 237]
 [  6  19   3   6   1   4   2   4   7 131]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test_pred,y_test.ravel()))




              precision    recall  f1-score   support

           0       0.56      0.35      0.43      1618
           1       0.23      0.63      0.34       366
           2       0.45      0.22      0.30      2055
           3       0.22      0.29      0.25       750
           4       0.46      0.25      0.32      1873
           5       0.22      0.41      0.29       538
           6       0.26      0.35      0.30       745
           7       0.22      0.69      0.33       311
           8       0.64      0.41      0.50      1561
           9       0.13      0.72      0.22       183

    accuracy                           0.34     10000
   macro avg       0.34      0.43      0.33     10000
weighted avg       0.44      0.34      0.35     10000

